POST http://localhost:8080/api/chirps HTTP/1.1
Content-Type: application/json
Header: application/json
Authorization: Bearer <JWT>
  
{
  "body": "This is a test chirpasdfsa dfasdf asdf kerfuffle"
}